// Dữ liệu từ điển ký hiệu toán học dùng trong đại số tuyến tính.
// Mỗi ký hiệu: tên VN/EN, ý nghĩa, và ĐẶC BIỆT là "dùng để tính/làm gì".
// Lưu ý: chuỗi tex viết trong string literal nên backslash phải nhân đôi:
//   '\\lambda' -> KaTeX nhận '\lambda'.

export interface WikiSymbol {
  tex: string; // ký hiệu chính, render bằng MathText
  name: string; // tên tiếng Việt
  en: string; // tên tiếng Anh
  category: string; // 1 trong các category id ở dưới
  meaning: string; // ý nghĩa ngắn gọn, dễ hiểu
  usedFor: string[]; // 2-4 gạch đầu dòng: DÙNG ĐỂ TÍNH/LÀM GÌ trong trường hợp cụ thể
  example?: { tex: string; note?: string }; // ví dụ ngắn (KaTeX block)
  seeChapter?: { id: string; lessonId: string; label: string }; // link học sâu
}

export interface WikiCategory {
  id: string;
  label: string;
}

export const CATEGORIES: WikiCategory[] = [
  { id: 'sets', label: 'Số & tập hợp' },
  { id: 'vector', label: 'Vector' },
  { id: 'matrix', label: 'Ma trận' },
  { id: 'spaces', label: 'Không gian vector' },
  { id: 'eigen-svd', label: 'Eigen & SVD' },
  { id: 'greek', label: 'Chữ Hy Lạp' },
];

export const SYMBOLS: WikiSymbol[] = [
  // ------------------------------------------------------------------
  // sets — Số & tập hợp
  // ------------------------------------------------------------------
  {
    tex: '\\mathbb{R}',
    name: 'Tập số thực',
    en: 'Real numbers',
    category: 'sets',
    meaning: 'Tập tất cả các số trên trục số: nguyên, phân số, vô tỉ (π, √2)…',
    usedFor: [
      'Khẳng định một đại lượng là số thực (vô hướng hợp lệ), vd hệ số co giãn',
      'Làm "nền" để định nghĩa vector, ma trận với phần tử là số thực',
      'Phân biệt với ℤ, ℚ khi cần miền giá trị liên tục',
    ],
    example: { tex: '\\pi \\in \\mathbb{R}, \\quad -3 \\in \\mathbb{R}', note: 'Mọi số trên trục số đều thuộc ℝ.' },
    seeChapter: { id: 'ch0-foundations', lessonId: 'notation', label: 'Chương 0: Ký hiệu toán học' },
  },
  {
    tex: '\\mathbb{R}^n',
    name: 'Không gian n chiều',
    en: 'n-dimensional space',
    category: 'sets',
    meaning: 'Tập các bộ gồm n số thực — chính là tập mọi vector n thành phần.',
    usedFor: [
      'Nói rõ một vector có bao nhiêu thành phần (v ∈ ℝ³ là vector 3 chiều)',
      'Xác định "sân chơi" của một biến đổi tuyến tính (đi từ ℝⁿ tới ℝᵐ)',
      'Đặt câu hỏi về span, cơ sở, số chiều của không gian',
    ],
    example: { tex: '(1,\\,2,\\,3) \\in \\mathbb{R}^3', note: 'Bộ 3 số = một điểm/vector trong không gian 3 chiều.' },
    seeChapter: { id: 'ch1-vectors', lessonId: 'intro', label: 'Chương 1: Vector là gì?' },
  },
  {
    tex: '\\mathbb{R}^{m\\times n}',
    name: 'Tập ma trận m×n',
    en: 'Matrices m by n',
    category: 'sets',
    meaning: 'Tập mọi ma trận thực có m hàng và n cột.',
    usedFor: [
      'Khai báo kích thước ma trận trước khi tính (A ∈ ℝ^{2×3})',
      'Kiểm tra hai ma trận có nhân được không (cột A khớp hàng B)',
      'Xác định biến đổi ℝⁿ → ℝᵐ tương ứng với ma trận',
    ],
    example: { tex: 'A \\in \\mathbb{R}^{2\\times 3}', note: 'A có 2 hàng, 3 cột → biến vector ℝ³ thành ℝ².' },
    seeChapter: { id: 'ch3-matrices', lessonId: 'transform', label: 'Chương 3: Ma trận = biến đổi' },
  },
  {
    tex: '\\mathbb{Z}',
    name: 'Tập số nguyên',
    en: 'Integers',
    category: 'sets',
    meaning: 'Các số …, −2, −1, 0, 1, 2, … (không có phần lẻ).',
    usedFor: [
      'Đánh chỉ số hàng/cột, số bước, số chiều (luôn là số nguyên)',
      'Phân biệt nghiệm nguyên với nghiệm thực khi giải hệ',
    ],
    example: { tex: '-2,\\,-1,\\,0,\\,1,\\,2 \\in \\mathbb{Z}' },
    seeChapter: { id: 'ch0-foundations', lessonId: 'notation', label: 'Chương 0: Ký hiệu toán học' },
  },
  {
    tex: '\\mathbb{N}',
    name: 'Tập số tự nhiên',
    en: 'Natural numbers',
    category: 'sets',
    meaning: 'Các số đếm 0, 1, 2, 3, … (không âm).',
    usedFor: [
      'Đếm số phần tử, số chiều, số lần lặp',
      'Làm mũ/lũy thừa của ma trận (Aⁿ với n ∈ ℕ)',
    ],
    example: { tex: '0,\\,1,\\,2,\\,3,\\,\\dots \\in \\mathbb{N}' },
  },
  {
    tex: '\\in',
    name: 'Thuộc',
    en: 'Is an element of',
    category: 'sets',
    meaning: 'Nói một phần tử nằm trong một tập hợp.',
    usedFor: [
      'Khẳng định x là phần tử của tập (3 ∈ ℝ)',
      'Nêu điều kiện trong định nghĩa (với mọi v ∈ ℝⁿ)',
    ],
    example: { tex: '3 \\in \\{1,\\,2,\\,3\\}' },
    seeChapter: { id: 'ch0-foundations', lessonId: 'notation', label: 'Chương 0: Ký hiệu toán học' },
  },
  {
    tex: '\\notin',
    name: 'Không thuộc',
    en: 'Is not an element of',
    category: 'sets',
    meaning: 'Phủ định của ∈: phần tử KHÔNG nằm trong tập.',
    usedFor: [
      'Chỉ ra một phần tử ngoài tập (½ ∉ ℤ)',
      'Nêu phản ví dụ để bác bỏ một khẳng định',
    ],
    example: { tex: '\\tfrac{1}{2} \\notin \\mathbb{Z}', note: '½ không phải số nguyên.' },
  },
  {
    tex: '\\subset',
    name: 'Tập con',
    en: 'Subset',
    category: 'sets',
    meaning: 'Mọi phần tử của tập này đều nằm trong tập kia.',
    usedFor: [
      'Diễn tả quan hệ lồng nhau giữa các tập số (ℤ ⊂ ℝ)',
      'Kiểm tra một subspace nằm trong không gian lớn hơn',
    ],
    example: { tex: '\\mathbb{Z} \\subset \\mathbb{R}' },
    seeChapter: { id: 'ch4-spaces', lessonId: 'subspace', label: 'Chương 4: Subspace' },
  },
  {
    tex: '\\subseteq',
    name: 'Tập con (hoặc bằng)',
    en: 'Subset or equal',
    category: 'sets',
    meaning: 'Như ⊂ nhưng cho phép hai tập bằng nhau.',
    usedFor: [
      'Phát biểu định nghĩa subspace: W ⊆ V',
      'Chứng minh hai tập bằng nhau (A ⊆ B và B ⊆ A)',
    ],
    example: { tex: 'W \\subseteq V' },
    seeChapter: { id: 'ch4-spaces', lessonId: 'subspace', label: 'Chương 4: Subspace' },
  },
  {
    tex: '\\forall',
    name: 'Với mọi',
    en: 'For all',
    category: 'sets',
    meaning: 'Khẳng định đúng cho mọi phần tử được xét.',
    usedFor: [
      'Viết gọn tính chất tổng quát (∀ v: ‖v‖ ≥ 0)',
      'Định nghĩa phép biến đổi tuyến tính cho mọi vector đầu vào',
    ],
    example: { tex: '\\forall x \\in \\mathbb{R}:\\ x^2 \\ge 0' },
    seeChapter: { id: 'ch0-foundations', lessonId: 'notation', label: 'Chương 0: Ký hiệu toán học' },
  },
  {
    tex: '\\exists',
    name: 'Tồn tại',
    en: 'There exists',
    category: 'sets',
    meaning: 'Có ít nhất một phần tử thỏa điều kiện.',
    usedFor: [
      'Khẳng định hệ có nghiệm (∃ x: Ax = b)',
      'Phát biểu tồn tại vector riêng, cơ sở…',
    ],
    example: { tex: '\\exists x \\in \\mathbb{R}:\\ x^2 = 2' },
  },
  {
    tex: '\\emptyset',
    name: 'Tập rỗng',
    en: 'Empty set',
    category: 'sets',
    meaning: 'Tập không chứa phần tử nào.',
    usedFor: [
      'Diễn tả hệ vô nghiệm (tập nghiệm = ∅)',
      'Nói hai tập không giao nhau (A ∩ B = ∅)',
    ],
    example: { tex: 'A \\cap B = \\emptyset' },
    seeChapter: { id: 'ch2-systems', lessonId: 'solutions', label: 'Chương 2: Duy nhất/vô số/vô nghiệm' },
  },
  {
    tex: '\\mapsto',
    name: 'Ánh xạ thành',
    en: 'Maps to',
    category: 'sets',
    meaning: 'Chỉ ra một phần tử được đưa tới phần tử nào qua một hàm.',
    usedFor: [
      'Mô tả quy tắc của hàm/biến đổi (x ↦ 2x)',
      'Diễn tả một ma trận biến vector v thành Av',
    ],
    example: { tex: 'x \\mapsto 2x', note: 'Đọc: x được ánh xạ thành 2x.' },
    seeChapter: { id: 'ch0-foundations', lessonId: 'functions', label: 'Chương 0: Hàm số & đồ thị' },
  },
  {
    tex: '\\Rightarrow',
    name: 'Suy ra',
    en: 'Implies',
    category: 'sets',
    meaning: 'Nếu vế trái đúng thì vế phải đúng.',
    usedFor: [
      'Nối các bước lập luận, chứng minh',
      'Diễn tả điều kiện đủ (det ≠ 0 ⇒ khả nghịch)',
    ],
    example: { tex: 'x > 2 \\Rightarrow x > 0' },
  },
  {
    tex: '\\Leftrightarrow',
    name: 'Tương đương',
    en: 'If and only if',
    category: 'sets',
    meaning: 'Hai vế cùng đúng hoặc cùng sai (điều kiện cần và đủ).',
    usedFor: [
      'Phát biểu tiêu chuẩn hai chiều (A khả nghịch ⇔ det A ≠ 0)',
      'Diễn tả u ⊥ v ⇔ u·v = 0',
    ],
    example: { tex: 'x^2 = 4 \\Leftrightarrow x = \\pm 2' },
  },
  {
    tex: '\\approx',
    name: 'Xấp xỉ',
    en: 'Approximately equal',
    category: 'sets',
    meaning: 'Hai giá trị gần bằng nhau (không chính xác tuyệt đối).',
    usedFor: [
      'Ghi giá trị làm tròn (π ≈ 3.14159)',
      'Diễn tả nghiệm số gần đúng, kết quả nén ảnh xấp xỉ ảnh gốc',
    ],
    example: { tex: '\\pi \\approx 3.14159' },
    seeChapter: { id: 'ch6-svd', lessonId: 'compression', label: 'Chương 6: Nén ảnh rank-k' },
  },
  {
    tex: '\\propto',
    name: 'Tỉ lệ với',
    en: 'Proportional to',
    category: 'sets',
    meaning: 'Đại lượng này bằng một hằng số nhân với đại lượng kia.',
    usedFor: [
      'Nói hai vector cùng phương (v ∝ w)',
      'Diễn tả quan hệ tỉ lệ trong mô hình (y ∝ x)',
    ],
    example: { tex: 'y \\propto x', note: 'y = k·x với hằng số k nào đó.' },
  },

  // ------------------------------------------------------------------
  // vector — Vector
  // ------------------------------------------------------------------
  {
    tex: '\\vec{v}',
    name: 'Vector',
    en: 'Vector',
    category: 'vector',
    meaning: 'Đại lượng có hướng và độ lớn; viết dưới dạng bộ số thành phần.',
    usedFor: [
      'Biểu diễn dịch chuyển, lực, hoặc một điểm trong không gian',
      'Cộng/trừ để gộp các dịch chuyển',
      'Làm đầu vào cho biến đổi tuyến tính (Av)',
    ],
    example: { tex: '\\vec{v} = (v_1,\\, v_2,\\, v_3)' },
    seeChapter: { id: 'ch1-vectors', lessonId: 'intro', label: 'Chương 1: Vector là gì?' },
  },
  {
    tex: '\\mathbf{v}',
    name: 'Vector (in đậm)',
    en: 'Vector (bold)',
    category: 'vector',
    meaning: 'Cách viết vector bằng chữ in đậm thay cho mũi tên — cùng ý nghĩa với v⃗.',
    usedFor: [
      'Ký hiệu vector gọn gàng trong văn bản in (sách, bài báo)',
      'Phân biệt vector (đậm) với vô hướng (thường)',
    ],
    example: { tex: '\\mathbf{v} = \\vec{v}' },
    seeChapter: { id: 'ch1-vectors', lessonId: 'intro', label: 'Chương 1: Vector là gì?' },
  },
  {
    tex: '\\|v\\|',
    name: 'Độ dài (norm)',
    en: 'Norm / magnitude',
    category: 'vector',
    meaning: 'Độ dài (độ lớn) của vector — khoảng cách từ gốc tới đầu mũi tên.',
    usedFor: [
      'Đo độ dài/độ lớn một vector',
      'Chuẩn hóa thành vector đơn vị v/‖v‖',
      'Tính khoảng cách giữa 2 điểm = ‖a − b‖',
    ],
    example: { tex: '\\|v\\| = \\sqrt{v_1^2 + v_2^2 + v_3^2}', note: 'Định lý Pythagoras mở rộng ra n chiều.' },
    seeChapter: { id: 'ch1-vectors', lessonId: 'dot', label: 'Chương 1: Dot product' },
  },
  {
    tex: '\\hat{v}',
    name: 'Vector đơn vị',
    en: 'Unit vector',
    category: 'vector',
    meaning: 'Vector cùng hướng với v nhưng độ dài đúng bằng 1.',
    usedFor: [
      'Chỉ hướng thuần túy, bỏ độ lớn',
      'Chuẩn hóa: v̂ = v / ‖v‖',
      'Tạo cơ sở trực chuẩn (các vector đơn vị vuông góc)',
    ],
    example: { tex: '\\hat{v} = \\dfrac{v}{\\|v\\|}' },
    seeChapter: { id: 'ch1-vectors', lessonId: 'scaling', label: 'Chương 1: Nhân vô hướng' },
  },
  {
    tex: 'u \\cdot v',
    name: 'Tích vô hướng',
    en: 'Dot product',
    category: 'vector',
    meaning: 'Nhân từng cặp thành phần rồi cộng lại — cho ra một số.',
    usedFor: [
      'Kiểm tra vuông góc: u·v = 0 ⇔ u ⊥ v',
      'Tính góc giữa hai vector qua cos θ',
      'Tính hình chiếu của vector này lên vector kia',
    ],
    example: { tex: 'u \\cdot v = u_1 v_1 + u_2 v_2 = \\|u\\|\\,\\|v\\|\\cos\\theta' },
    seeChapter: { id: 'ch1-vectors', lessonId: 'dot', label: 'Chương 1: Dot product' },
  },
  {
    tex: 'u \\times v',
    name: 'Tích có hướng',
    en: 'Cross product',
    category: 'vector',
    meaning: 'Trong 3D, cho ra vector vuông góc với cả u và v.',
    usedFor: [
      'Tìm vector pháp tuyến của một mặt phẳng',
      'Tính diện tích hình bình hành = ‖u × v‖',
      'Xác định chiều xoay (quy tắc bàn tay phải)',
    ],
    example: { tex: '\\|u \\times v\\| = \\|u\\|\\,\\|v\\|\\sin\\theta' },
    seeChapter: { id: 'ch1-vectors', lessonId: 'cross', label: 'Chương 1: Cross product' },
  },
  {
    tex: '\\perp',
    name: 'Vuông góc',
    en: 'Perpendicular',
    category: 'vector',
    meaning: 'Hai vector (hay đường/mặt) tạo góc 90°.',
    usedFor: [
      'Diễn tả u ⊥ v khi u·v = 0',
      'Mô tả cơ sở trực giao, phần bù trực giao',
    ],
    example: { tex: 'u \\perp v \\iff u \\cdot v = 0' },
    seeChapter: { id: 'ch1-vectors', lessonId: 'dot', label: 'Chương 1: Dot product' },
  },
  {
    tex: '\\parallel',
    name: 'Song song',
    en: 'Parallel',
    category: 'vector',
    meaning: 'Hai vector cùng phương (tỉ lệ với nhau).',
    usedFor: [
      'Diễn tả u ∥ v khi u = k·v',
      'Nhận biết vector phụ thuộc tuyến tính trong 2D',
    ],
    example: { tex: 'u \\parallel v' },
  },
  {
    tex: '\\theta',
    name: 'Góc giữa hai vector',
    en: 'Angle',
    category: 'vector',
    meaning: 'Góc hình học giữa hai vector, tính từ tích vô hướng.',
    usedFor: [
      'Đo độ "giống hướng" của hai vector (θ nhỏ ⇒ cùng hướng)',
      'Suy ra vuông góc khi θ = 90°',
    ],
    example: { tex: '\\cos\\theta = \\dfrac{u \\cdot v}{\\|u\\|\\,\\|v\\|}' },
    seeChapter: { id: 'ch1-vectors', lessonId: 'dot', label: 'Chương 1: Dot product' },
  },
  {
    tex: '\\langle u, v\\rangle',
    name: 'Tích trong',
    en: 'Inner product',
    category: 'vector',
    meaning: 'Tổng quát của dot product; trong ℝⁿ chính là u·v.',
    usedFor: [
      'Định nghĩa độ dài và góc một cách trừu tượng',
      'Xây khái niệm trực giao trong không gian tổng quát',
    ],
    example: { tex: '\\langle u, v\\rangle = u \\cdot v' },
    seeChapter: { id: 'ch1-vectors', lessonId: 'dot', label: 'Chương 1: Dot product' },
  },
  {
    tex: '\\text{proj}_{b}(a)',
    name: 'Hình chiếu',
    en: 'Projection',
    category: 'vector',
    meaning: 'Cái bóng của vector a khi chiếu vuông góc lên vector b.',
    usedFor: [
      'Tách a thành phần song song và phần vuông góc với b',
      'Tìm điểm gần nhất trên một đường/mặt (nền tảng least squares)',
    ],
    example: { tex: '\\text{proj}_{b}(a) = \\dfrac{a \\cdot b}{b \\cdot b}\\, b' },
    seeChapter: { id: 'ch7-code', lessonId: 'least-squares', label: 'Chương 7: Least squares fit' },
  },
  {
    tex: '\\sum',
    name: 'Tổng sigma',
    en: 'Summation',
    category: 'vector',
    meaning: 'Viết gọn phép cộng dồn nhiều số hạng.',
    usedFor: [
      'Cộng dồn để định nghĩa dot product, chuẩn, trung bình',
      'Diễn tả tổng của một dãy theo chỉ số chạy',
    ],
    example: { tex: '\\sum_{i=1}^{n} i = \\dfrac{n(n+1)}{2}' },
    seeChapter: { id: 'ch0-foundations', lessonId: 'notation', label: 'Chương 0: Ký hiệu toán học' },
  },
  {
    tex: '\\prod',
    name: 'Tích pi',
    en: 'Product',
    category: 'vector',
    meaning: 'Viết gọn phép nhân dồn nhiều thừa số.',
    usedFor: [
      'Diễn tả tích nhiều số hạng (giai thừa, tích các trị riêng)',
      'det của ma trận tam giác = tích các phần tử đường chéo',
    ],
    example: { tex: '\\prod_{i=1}^{n} i = n!' },
  },
  {
    tex: '\\sqrt{x}',
    name: 'Căn bậc hai',
    en: 'Square root',
    category: 'vector',
    meaning: 'Số không âm mà bình phương lên bằng x.',
    usedFor: [
      'Tính độ dài vector ‖v‖ = √(v·v)',
      'Suy singular value σ = √(trị riêng của AᵀA)',
    ],
    example: { tex: '\\sqrt{9} = 3' },
  },

  // ------------------------------------------------------------------
  // matrix — Ma trận
  // ------------------------------------------------------------------
  {
    tex: 'A',
    name: 'Ma trận',
    en: 'Matrix',
    category: 'matrix',
    meaning: 'Bảng số chữ nhật; đại diện cho một biến đổi tuyến tính hoặc một hệ.',
    usedFor: [
      'Lưu hệ số của hệ phương trình',
      'Biến đổi vector: v ↦ Av (xoay, co giãn, chiếu…)',
      'Ghép cột thành các vector để xét span',
    ],
    example: { tex: 'A = \\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}' },
    seeChapter: { id: 'ch3-matrices', lessonId: 'transform', label: 'Chương 3: Ma trận = biến đổi' },
  },
  {
    tex: 'A^T',
    name: 'Ma trận chuyển vị',
    en: 'Transpose',
    category: 'matrix',
    meaning: 'Lật ma trận qua đường chéo: hàng thành cột và ngược lại.',
    usedFor: [
      'Đổi vector cột thành vector hàng',
      'Lập AᵀA trong least squares và SVD',
      'Kiểm tra đối xứng: A = Aᵀ',
    ],
    example: { tex: '\\begin{pmatrix} 1 & 2 \\\\ 3 & 4 \\end{pmatrix}^T = \\begin{pmatrix} 1 & 3 \\\\ 2 & 4 \\end{pmatrix}' },
    seeChapter: { id: 'ch3-matrices', lessonId: 'special', label: 'Chương 3: Ma trận đặc biệt' },
  },
  {
    tex: 'A^{-1}',
    name: 'Ma trận nghịch đảo',
    en: 'Inverse',
    category: 'matrix',
    meaning: 'Ma trận "hoàn tác" A: nhân vào cho ra ma trận đơn vị.',
    usedFor: [
      'Giải hệ Ax = b bằng x = A⁻¹b (khi A khả nghịch)',
      'Đảo ngược một biến đổi tuyến tính',
      'Đổi cơ sở ngược lại',
    ],
    example: { tex: 'A A^{-1} = A^{-1} A = I' },
    seeChapter: { id: 'ch3-matrices', lessonId: 'inverse', label: 'Chương 3: Ma trận nghịch đảo' },
  },
  {
    tex: 'I',
    name: 'Ma trận đơn vị',
    en: 'Identity matrix',
    category: 'matrix',
    meaning: 'Đường chéo toàn 1, còn lại là 0; nhân vào không đổi gì.',
    usedFor: [
      'Đóng vai trò "số 1" cho ma trận: AI = A',
      'Định nghĩa nghịch đảo (AA⁻¹ = I)',
      'Xuất hiện trong det(A − λI) khi tìm trị riêng',
    ],
    example: { tex: 'I = \\begin{pmatrix} 1 & 0 \\\\ 0 & 1 \\end{pmatrix}' },
    seeChapter: { id: 'ch3-matrices', lessonId: 'special', label: 'Chương 3: Ma trận đặc biệt' },
  },
  {
    tex: '\\det(A)',
    name: 'Định thức',
    en: 'Determinant',
    category: 'matrix',
    meaning: 'Một con số đo mức phóng đại diện tích/thể tích của biến đổi A.',
    usedFor: [
      'Kiểm tra ma trận có khả nghịch không (det ≠ 0)',
      'Tính hệ số phóng đại diện tích/thể tích của biến đổi',
      'Xác định hệ phương trình có nghiệm duy nhất',
    ],
    example: { tex: '\\det\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix} = ad - bc' },
    seeChapter: { id: 'ch3-matrices', lessonId: 'determinant', label: 'Chương 3: Determinant' },
  },
  {
    tex: '|A|',
    name: 'Định thức (viết tắt)',
    en: 'Determinant (bars)',
    category: 'matrix',
    meaning: 'Cách viết gọn của det(A) bằng hai vạch đứng.',
    usedFor: [
      'Ghi định thức nhanh trong công thức',
      'Không nhầm với chuẩn: |A| là số phóng đại thể tích, không phải độ dài',
    ],
    example: { tex: '|A| = \\det(A)' },
    seeChapter: { id: 'ch3-matrices', lessonId: 'determinant', label: 'Chương 3: Determinant' },
  },
  {
    tex: '\\text{tr}(A)',
    name: 'Vết',
    en: 'Trace',
    category: 'matrix',
    meaning: 'Tổng các phần tử trên đường chéo chính.',
    usedFor: [
      'Bằng tổng các trị riêng (tr A = Σλᵢ)',
      'Kiểm tra nhanh khi tìm trị riêng ma trận 2×2',
    ],
    example: { tex: '\\text{tr}\\begin{pmatrix} 1 & 2 \\\\ 3 & 4 \\end{pmatrix} = 1 + 4 = 5' },
    seeChapter: { id: 'ch5-eigen', lessonId: 'characteristic', label: 'Chương 5: Phương trình đặc trưng' },
  },
  {
    tex: '\\text{rank}(A)',
    name: 'Hạng',
    en: 'Rank',
    category: 'matrix',
    meaning: 'Số cột (hay hàng) độc lập tuyến tính — số chiều thực sự của ảnh.',
    usedFor: [
      'Biết biến đổi "ép" không gian xuống mấy chiều',
      'Đếm số nghiệm của hệ (đủ hạng ⇒ nghiệm duy nhất)',
      'Chọn số thành phần khi nén ảnh rank-k',
    ],
    example: { tex: '\\text{rank}\\begin{pmatrix} 1 & 2 \\\\ 2 & 4 \\end{pmatrix} = 1', note: 'Cột 2 = 2×cột 1 nên chỉ 1 cột độc lập.' },
    seeChapter: { id: 'ch4-spaces', lessonId: 'rank', label: 'Chương 4: Rank' },
  },
  {
    tex: 'A_{ij}',
    name: 'Phần tử ma trận',
    en: 'Matrix entry',
    category: 'matrix',
    meaning: 'Số nằm ở hàng i, cột j của ma trận A.',
    usedFor: [
      'Truy cập một ô cụ thể khi tính tay hoặc lập trình',
      'Viết công thức tổng quát cho phép nhân ma trận',
    ],
    example: { tex: '(AB)_{ij} = \\sum_{k} A_{ik} B_{kj}', note: 'Phần tử (i,j) của tích = dot của hàng i với cột j.' },
    seeChapter: { id: 'ch3-matrices', lessonId: 'composition', label: 'Chương 3: Nhân ma trận' },
  },
  {
    tex: '\\text{diag}(d_1,\\dots,d_n)',
    name: 'Ma trận đường chéo',
    en: 'Diagonal matrix',
    category: 'matrix',
    meaning: 'Ma trận chỉ có phần tử trên đường chéo, còn lại bằng 0.',
    usedFor: [
      'Co giãn từng trục độc lập (mỗi dᵢ giãn một hướng)',
      'Là dạng D trong chéo hóa A = PDP⁻¹, cực dễ tính lũy thừa',
    ],
    example: { tex: '\\text{diag}(2,\\,5) = \\begin{pmatrix} 2 & 0 \\\\ 0 & 5 \\end{pmatrix}' },
    seeChapter: { id: 'ch5-eigen', lessonId: 'diagonalization', label: 'Chương 5: Diagonalization' },
  },
  {
    tex: '\\mathbf{0}',
    name: 'Ma trận / vector không',
    en: 'Zero matrix / vector',
    category: 'matrix',
    meaning: 'Mọi phần tử đều bằng 0.',
    usedFor: [
      'Đóng vai trò "số 0" khi cộng (A + 0 = A)',
      'Vế phải của hệ thuần nhất Ax = 0 (định nghĩa null space)',
    ],
    example: { tex: '\\mathbf{0} = \\begin{pmatrix} 0 & 0 \\\\ 0 & 0 \\end{pmatrix}' },
    seeChapter: { id: 'ch4-spaces', lessonId: 'colnull', label: 'Chương 4: Column & Null space' },
  },
  {
    tex: 'AB',
    name: 'Nhân ma trận',
    en: 'Matrix multiplication',
    category: 'matrix',
    meaning: 'Ghép hai biến đổi: làm B trước, rồi A (đọc từ phải sang trái).',
    usedFor: [
      'Hợp nhiều biến đổi thành một ma trận duy nhất',
      'Chú ý: nói chung AB ≠ BA (không giao hoán)',
    ],
    example: { tex: '(AB)C = A(BC)', note: 'Kết hợp được, nhưng thứ tự thì không đổi tùy tiện.' },
    seeChapter: { id: 'ch3-matrices', lessonId: 'composition', label: 'Chương 3: Nhân ma trận' },
  },
  {
    tex: 'A \\sim B',
    name: 'Tương đương hàng',
    en: 'Row equivalent',
    category: 'matrix',
    meaning: 'B nhận được từ A qua các phép biến đổi hàng sơ cấp.',
    usedFor: [
      'Rút gọn ma trận về dạng bậc thang khi khử Gauss',
      'Bảo toàn tập nghiệm của hệ trong lúc rút gọn',
    ],
    example: { tex: 'A \\sim B \\ \\Rightarrow\\ \\text{cùng tập nghiệm}' },
    seeChapter: { id: 'ch2-systems', lessonId: 'gauss', label: 'Chương 2: Khử Gauss' },
  },

  // ------------------------------------------------------------------
  // spaces — Không gian vector
  // ------------------------------------------------------------------
  {
    tex: '\\text{span}',
    name: 'Không gian sinh',
    en: 'Span',
    category: 'spaces',
    meaning: 'Tập tất cả tổ hợp tuyến tính của một nhóm vector.',
    usedFor: [
      'Mô tả "vùng phủ được" bởi vài vector (đường, mặt phẳng…)',
      'Kiểm tra một vector có nằm trong tầm với hay không',
    ],
    example: { tex: '\\text{span}\\{v_1,\\, v_2\\} = \\{\\,a v_1 + b v_2 \\,\\}' },
    seeChapter: { id: 'ch1-vectors', lessonId: 'combination', label: 'Chương 1: Combination & Span' },
  },
  {
    tex: '\\dim',
    name: 'Số chiều',
    en: 'Dimension',
    category: 'spaces',
    meaning: 'Số vector trong một cơ sở — số "hướng độc lập" của không gian.',
    usedFor: [
      'Đo độ lớn thực sự của một không gian con',
      'Áp dụng định lý hạng: dim Col + dim Nul = số cột',
    ],
    example: { tex: '\\dim \\mathbb{R}^n = n' },
    seeChapter: { id: 'ch4-spaces', lessonId: 'basis', label: 'Chương 4: Basis & Dimension' },
  },
  {
    tex: 'C(A)',
    name: 'Không gian cột',
    en: 'Column space',
    category: 'spaces',
    meaning: 'Span của các cột của A — chính là tập mọi giá trị Ax có thể đạt.',
    usedFor: [
      'Xác định b nào khiến Ax = b có nghiệm (b ∈ C(A))',
      'Biết "ảnh" của biến đổi A phủ được vùng nào',
    ],
    example: { tex: 'C(A) = \\{\\, Ax : x \\in \\mathbb{R}^n \\,\\}' },
    seeChapter: { id: 'ch4-spaces', lessonId: 'colnull', label: 'Chương 4: Column & Null space' },
  },
  {
    tex: 'N(A)',
    name: 'Không gian null',
    en: 'Null space',
    category: 'spaces',
    meaning: 'Tập mọi vector x bị A ép về 0.',
    usedFor: [
      'Tìm nghiệm của hệ thuần nhất Ax = 0',
      'Đo mức "mất thông tin" của biến đổi (null space càng lớn càng ép mạnh)',
    ],
    example: { tex: 'N(A) = \\{\\, x : Ax = 0 \\,\\}' },
    seeChapter: { id: 'ch4-spaces', lessonId: 'colnull', label: 'Chương 4: Column & Null space' },
  },
  {
    tex: 'R(A)',
    name: 'Không gian hàng',
    en: 'Row space',
    category: 'spaces',
    meaning: 'Span của các hàng của A; bằng không gian cột của Aᵀ.',
    usedFor: [
      'Xác định các ràng buộc độc lập trong hệ phương trình',
      'Cùng số chiều với column space (= rank)',
    ],
    example: { tex: 'R(A) = C(A^T)' },
    seeChapter: { id: 'ch4-spaces', lessonId: 'colnull', label: 'Chương 4: Column & Null space' },
  },
  {
    tex: '\\oplus',
    name: 'Tổng trực tiếp',
    en: 'Direct sum',
    category: 'spaces',
    meaning: 'Ghép hai không gian con chỉ giao nhau ở vector 0.',
    usedFor: [
      'Tách một không gian thành các phần độc lập (V = U ⊕ W)',
      'Phân tích vector duy nhất thành phần song song + vuông góc',
    ],
    example: { tex: '\\mathbb{R}^3 = U \\oplus W' },
    seeChapter: { id: 'ch4-spaces', lessonId: 'subspace', label: 'Chương 4: Subspace' },
  },
  {
    tex: '\\text{Col}(A)',
    name: 'Không gian cột (viết đủ)',
    en: 'Column space',
    category: 'spaces',
    meaning: 'Cách viết khác của C(A) — span các cột của A.',
    usedFor: [
      'Ghi rõ ràng khi trình bày (đồng nghĩa C(A))',
      'Xét khả năng có nghiệm của Ax = b',
    ],
    example: { tex: '\\text{Col}(A) = C(A)' },
    seeChapter: { id: 'ch4-spaces', lessonId: 'colnull', label: 'Chương 4: Column & Null space' },
  },
  {
    tex: '\\text{Nul}(A)',
    name: 'Không gian null (viết đủ)',
    en: 'Null space',
    category: 'spaces',
    meaning: 'Cách viết khác của N(A) — nghiệm của Ax = 0.',
    usedFor: [
      'Ghi rõ ràng khi trình bày (đồng nghĩa N(A))',
      'Tìm nghiệm tự do của hệ thuần nhất',
    ],
    example: { tex: '\\text{Nul}(A) = N(A)' },
    seeChapter: { id: 'ch4-spaces', lessonId: 'colnull', label: 'Chương 4: Column & Null space' },
  },
  {
    tex: '\\{v_1,\\dots,v_n\\}',
    name: 'Cơ sở',
    en: 'Basis',
    category: 'spaces',
    meaning: 'Bộ vector độc lập tuyến tính và sinh ra toàn bộ không gian.',
    usedFor: [
      'Làm "hệ trục" để viết mọi vector bằng tọa độ',
      'Số vector trong cơ sở = số chiều',
      'Đổi cơ sở để nhìn bài toán ở góc thuận lợi hơn',
    ],
    example: { tex: '\\{v_1,\\, \\dots,\\, v_n\\}' },
    seeChapter: { id: 'ch4-spaces', lessonId: 'basis', label: 'Chương 4: Basis & Dimension' },
  },

  // ------------------------------------------------------------------
  // eigen-svd — Eigen & SVD
  // ------------------------------------------------------------------
  {
    tex: '\\lambda',
    name: 'Trị riêng',
    en: 'Eigenvalue',
    category: 'eigen-svd',
    meaning: 'Hệ số co giãn của A dọc theo một hướng bất biến (vector riêng).',
    usedFor: [
      'Biết A kéo giãn/nén bao nhiêu lần trên mỗi hướng riêng',
      'Đưa A về dạng chéo để tính Aⁿ dễ dàng',
      'Phân tích ổn định của hệ động lực (|λ| < 1 hay > 1)',
    ],
    example: { tex: 'A v = \\lambda v', note: 'A chỉ kéo dài v (không đổi hướng) đúng λ lần.' },
    seeChapter: { id: 'ch5-eigen', lessonId: 'discover', label: 'Chương 5: Tìm hướng bất biến' },
  },
  {
    tex: '\\sigma',
    name: 'Giá trị kỳ dị',
    en: 'Singular value',
    category: 'eigen-svd',
    meaning: 'Hệ số co giãn của A theo các trục chính (luôn ≥ 0).',
    usedFor: [
      'Đo "độ quan trọng" của từng thành phần trong SVD',
      'Giữ vài σ lớn nhất để nén ảnh/dữ liệu (rank-k)',
      'Tính chuẩn và số điều kiện của ma trận',
    ],
    example: { tex: '\\sigma_i = \\sqrt{\\lambda_i(A^T A)}' },
    seeChapter: { id: 'ch6-svd', lessonId: 'singular', label: 'Chương 6: Singular values' },
  },
  {
    tex: '\\Sigma',
    name: 'Ma trận kỳ dị (Sigma hoa)',
    en: 'Sigma matrix',
    category: 'eigen-svd',
    meaning: 'Ma trận đường chéo chứa các singular value trong SVD.',
    usedFor: [
      'Là phần "co giãn" giữa hai phép xoay U và Vᵀ',
      'Cắt bớt để lấy xấp xỉ hạng thấp',
    ],
    example: { tex: '\\Sigma = \\text{diag}(\\sigma_1,\\, \\dots,\\, \\sigma_r)' },
    seeChapter: { id: 'ch6-svd', lessonId: 'singular', label: 'Chương 6: Singular values' },
  },
  {
    tex: '\\det(A - \\lambda I)',
    name: 'Đa thức đặc trưng',
    en: 'Characteristic polynomial',
    category: 'eigen-svd',
    meaning: 'Biểu thức mà nghiệm của nó chính là các trị riêng.',
    usedFor: [
      'Tìm trị riêng bằng cách giải det(A − λI) = 0',
      'Bậc của đa thức = kích thước ma trận = số trị riêng (kể bội)',
    ],
    example: { tex: '\\det(A - \\lambda I) = 0' },
    seeChapter: { id: 'ch5-eigen', lessonId: 'characteristic', label: 'Chương 5: Phương trình đặc trưng' },
  },
  {
    tex: 'A = P D P^{-1}',
    name: 'Chéo hóa',
    en: 'Diagonalization',
    category: 'eigen-svd',
    meaning: 'Viết A qua ma trận vector riêng P và ma trận chéo trị riêng D.',
    usedFor: [
      'Tính lũy thừa nhanh: Aⁿ = P Dⁿ P⁻¹',
      'Hiểu A như "đổi cơ sở → co giãn → đổi lại"',
      'Giải hệ vi phân, chuỗi Fibonacci bằng ma trận',
    ],
    example: { tex: 'A = P D P^{-1}, \\quad A^n = P D^n P^{-1}' },
    seeChapter: { id: 'ch5-eigen', lessonId: 'diagonalization', label: 'Chương 5: Diagonalization' },
  },
  {
    tex: 'A = U \\Sigma V^T',
    name: 'Phân tích SVD',
    en: 'Singular Value Decomposition',
    category: 'eigen-svd',
    meaning: 'Mọi ma trận = xoay (Vᵀ) → co giãn (Σ) → xoay (U).',
    usedFor: [
      'Phân tích BẤT KỲ ma trận nào (kể cả không vuông)',
      'Nén ảnh/dữ liệu bằng cách giữ vài σ lớn nhất',
      'Nền tảng của PCA và least squares',
    ],
    example: { tex: 'A = U \\Sigma V^T' },
    seeChapter: { id: 'ch6-svd', lessonId: 'singular', label: 'Chương 6: Singular values' },
  },
  {
    tex: 'A v = \\lambda v',
    name: 'Phương trình trị riêng',
    en: 'Eigenvalue equation',
    category: 'eigen-svd',
    meaning: 'Vector v mà A chỉ kéo giãn (không xoay) đúng λ lần.',
    usedFor: [
      'Định nghĩa vector riêng v và trị riêng λ',
      'Điểm khởi đầu để suy ra det(A − λI) = 0',
    ],
    example: { tex: 'A v = \\lambda v, \\quad v \\ne 0' },
    seeChapter: { id: 'ch5-eigen', lessonId: 'discover', label: 'Chương 5: Tìm hướng bất biến' },
  },
  {
    tex: '\\Lambda',
    name: 'Ma trận trị riêng (Lambda hoa)',
    en: 'Eigenvalue matrix',
    category: 'eigen-svd',
    meaning: 'Ma trận chéo chứa các trị riêng λ (chính là D trong A = PΛP⁻¹).',
    usedFor: [
      'Gom mọi trị riêng vào một ma trận chéo',
      'Viết gọn dạng chéo hóa A = PΛP⁻¹',
    ],
    example: { tex: '\\Lambda = \\text{diag}(\\lambda_1,\\, \\dots,\\, \\lambda_n)' },
    seeChapter: { id: 'ch5-eigen', lessonId: 'diagonalization', label: 'Chương 5: Diagonalization' },
  },

  // ------------------------------------------------------------------
  // greek — Chữ Hy Lạp hay gặp
  // ------------------------------------------------------------------
  {
    tex: '\\alpha',
    name: 'Alpha',
    en: 'Alpha',
    category: 'greek',
    meaning: 'Thường là một vô hướng (hệ số) trong tổ hợp tuyến tính.',
    usedFor: [
      'Ký hiệu hệ số nhân vector: αv',
      'Đặt tên tham số, tốc độ học (learning rate) trong ứng dụng',
    ],
    example: { tex: '\\alpha v_1 + \\beta v_2' },
    seeChapter: { id: 'ch1-vectors', lessonId: 'combination', label: 'Chương 1: Combination & Span' },
  },
  {
    tex: '\\beta',
    name: 'Beta',
    en: 'Beta',
    category: 'greek',
    meaning: 'Thường là vô hướng thứ hai đi kèm α trong tổ hợp tuyến tính.',
    usedFor: [
      'Hệ số cho vector thứ hai: βv₂',
      'Tham số hồi quy trong least squares',
    ],
    example: { tex: '\\alpha v_1 + \\beta v_2' },
    seeChapter: { id: 'ch1-vectors', lessonId: 'combination', label: 'Chương 1: Combination & Span' },
  },
  {
    tex: '\\theta',
    name: 'Theta',
    en: 'Theta',
    category: 'greek',
    meaning: 'Thường ký hiệu một góc (giữa hai vector, hoặc góc xoay).',
    usedFor: [
      'Góc giữa hai vector trong công thức cos θ',
      'Góc xoay trong ma trận quay 2D',
    ],
    example: { tex: 'R(\\theta) = \\begin{pmatrix} \\cos\\theta & -\\sin\\theta \\\\ \\sin\\theta & \\cos\\theta \\end{pmatrix}' },
    seeChapter: { id: 'ch0-foundations', lessonId: 'trig', label: 'Chương 0: sin & cos' },
  },
  {
    tex: '\\lambda',
    name: 'Lambda',
    en: 'Lambda',
    category: 'greek',
    meaning: 'Trong ĐSTT hầu như luôn là trị riêng (eigenvalue).',
    usedFor: [
      'Ký hiệu trị riêng trong Av = λv',
      'Ẩn số trong đa thức đặc trưng det(A − λI) = 0',
    ],
    example: { tex: 'A v = \\lambda v' },
    seeChapter: { id: 'ch5-eigen', lessonId: 'discover', label: 'Chương 5: Tìm hướng bất biến' },
  },
  {
    tex: '\\sigma',
    name: 'Sigma (thường)',
    en: 'Sigma (lowercase)',
    category: 'greek',
    meaning: 'Trong ĐSTT là singular value; trong thống kê là độ lệch chuẩn.',
    usedFor: [
      'Ký hiệu singular value σᵢ trong SVD',
      'Độ lệch chuẩn khi làm PCA trên dữ liệu',
    ],
    example: { tex: '\\sigma_1 \\ge \\sigma_2 \\ge \\dots \\ge 0' },
    seeChapter: { id: 'ch6-svd', lessonId: 'pca', label: 'Chương 6: PCA sơ lược' },
  },
  {
    tex: '\\Sigma',
    name: 'Sigma (hoa)',
    en: 'Sigma (uppercase)',
    category: 'greek',
    meaning: 'Ký hiệu tổng ∑; hoặc ma trận singular value trong SVD; hoặc ma trận hiệp phương sai.',
    usedFor: [
      'Viết tổng dồn ∑ (dot product, trung bình)',
      'Ma trận Σ chứa các σ trong A = UΣVᵀ',
    ],
    example: { tex: '\\sum_{i=1}^{n} x_i \\quad\\text{và}\\quad A = U\\Sigma V^T' },
    seeChapter: { id: 'ch6-svd', lessonId: 'singular', label: 'Chương 6: Singular values' },
  },
  {
    tex: '\\Delta',
    name: 'Delta (hoa)',
    en: 'Delta (uppercase)',
    category: 'greek',
    meaning: 'Thường chỉ "độ thay đổi" của một đại lượng, hoặc biệt thức.',
    usedFor: [
      'Ký hiệu số gia Δx, Δv (thay đổi nhỏ)',
      'Biệt thức Δ = b² − 4ac khi giải đa thức đặc trưng 2×2',
    ],
    example: { tex: '\\Delta = b^2 - 4ac' },
    seeChapter: { id: 'ch5-eigen', lessonId: 'characteristic', label: 'Chương 5: Phương trình đặc trưng' },
  },
  {
    tex: '\\pi',
    name: 'Pi',
    en: 'Pi',
    category: 'greek',
    meaning: 'Hằng số ≈ 3.14159, tỉ số chu vi trên đường kính.',
    usedFor: [
      'Đo góc bằng radian (nửa vòng = π)',
      'Xuất hiện trong ma trận xoay khi góc tính theo radian',
    ],
    example: { tex: '\\pi \\approx 3.14159' },
    seeChapter: { id: 'ch0-foundations', lessonId: 'trig', label: 'Chương 0: sin & cos' },
  },
  {
    tex: '\\phi',
    name: 'Phi',
    en: 'Phi',
    category: 'greek',
    meaning: 'Thường là một góc, hoặc tỉ lệ vàng φ ≈ 1.618.',
    usedFor: [
      'Ký hiệu góc thứ hai (bên cạnh θ)',
      'Tỉ lệ vàng xuất hiện khi giải Fibonacci bằng trị riêng',
    ],
    example: { tex: '\\phi = \\dfrac{1 + \\sqrt{5}}{2} \\approx 1.618' },
    seeChapter: { id: 'ch5-eigen', lessonId: 'powers', label: 'Chương 5: Lũy thừa & Fibonacci' },
  },
  {
    tex: '\\mu',
    name: 'Mu',
    en: 'Mu',
    category: 'greek',
    meaning: 'Thường là giá trị trung bình (mean) của dữ liệu.',
    usedFor: [
      'Ký hiệu trung bình μ khi chuẩn hóa dữ liệu',
      'Trừ trung bình (center) trước khi làm PCA',
    ],
    example: { tex: '\\mu = \\dfrac{1}{n}\\sum_{i=1}^{n} x_i' },
    seeChapter: { id: 'ch6-svd', lessonId: 'pca', label: 'Chương 6: PCA sơ lược' },
  },
];
